### ISSUE TITLE
Blackspace on the bottom of files for some themes

### ISSUE THREAD

**Issue by oeuvars** [andrew-george/Noir-vscode-theme#2]
As it is seen on this file, containing a few lines of code, a visible blackspace can be seen.
![Screenshot 2024-03-24 at 16 33 43](https://github.com/andrew-george/Noir-vscode-theme/assets/102863478/632dcf1b-5b2c-47a2-8cf8-613157cd8fc8)
However, if the no. of lines in a file increase it goes away.
![Screenshot 2024-03-24 at 16 34 14](https://github.com/andrew-george/Noir-vscode-theme/assets/102863478/00fcbc85-353e-4946-a51f-0750bbf23562)

This is not a dealbreaker, but something i noticed using Noir themes on a daily basis. Also to mention this is not happening for black and lighter themes of Noir, only the grey and the darker ones.

**Comment by andrewberty** [comment]
Hi there,

I can't replicate that acutally, I'm not having that darker space in any of them so maybe some setting in your vscode config is responsible for certain editor height therefore another color group is visible underneath.

can you please share your settings.json and let's think about what may be causing this.

**Comment by oeuvars** [comment]
Yes, here is my settings.json
`{
    "security.workspace.trust.untrustedFiles": "open",
    "files.trimTrailingWhitespace": true,
    "files.insertFinalNewline": true,
    "editor.rulers": [
        120
    ],
    "explorer.confirmDelete": false,
    "editor.minimap.enabled": false,
    "terminal.explorerKind": "external",
    "terminal.integrated.allowMnemonics": true,
    "terminal.integrated.cursorStyle": "line",
    "emmet.triggerExpansionOnTab": true,
    "workbench.settings.openDefaultKeybindings": true,
    "debug.onTaskErrors": "debugAnyway",
    "editor.fontWeight": 400,
    "editor.scrollBeyondLastLine": false,
    "files.autoSaveDelay": 1,
    "terminal.integrated.fontWeight": 400,
    "terminal.integrated.fontWeightBold": 400,
    "terminal.integrated.lineHeight": 1.3,
    "editor.lineHeight": 1.5,
    "editor.tokenColorCustomizations": {

        "[Rosé Pine]": {
            "textMateRules": [
                {
                    "scope": [
                        "comment",
                        "entity.other.attribute-name",
                        "entity.other.inherited-class",
                        "support.function",
                        "variable",
                        "meta.directive.vue"
                    ],
                    "settings": {
                        "fontStyle": "bold"
                    }
                }
            ]
        },
        "textMateRules": [
            {
                "name": "One Dark italic",
                "scope": [
                    "comment",
                    "entity.other.attribute-name",
                    "keyword",
                    "markup.underline.link",
                    "storage.modifier",
                    "storage.type",
                    "string.url",
                    "variable.language.super",
                    "variable.language.this"
                ],
                "settings": {
                    "fontStyle": "italic"
                }
            },
            {
                "name": "One Dark italic reset",
                "scope": [
                    "keyword.operator",
                    "keyword.other.type",
                    "storage.modifier.import",
                    "storage.modifier.package",
                    "storage.type.built-in",
                    "storage.type.function.arrow",
                    "storage.type.generic",
                    "storage.type.java",
                    "storage.type.primitive"
                ],
                "settings": {
                    "fontStyle": ""
                }
            }
        ]
    },
    "tailwindCSS.experimental.configFile": null,
    "editor.quickSuggestions": {
        "strings": "on"
    },
    "editor.linkedEditing": true,
    "terminal.integrated.gpuAcceleration": "off",
    "terminal.integrated.autoReplies": {

    },
    "editor.fontVariations": false,
    "workbench.startupEditor": "none",
    "javascript.updateImportsOnFileMove.enabled": "always",
    "editor.accessibilitySupport": "off",
    "git.autofetch": true,
    "editor.inlayHints.fontFamily": "Helvetica",
    "terminal.integrated.enableMultiLinePasteWarning": false,
    "workbench.iconTheme": "helium-icon-theme",
    "editor.fontFamily": "Cartograph CF, 'Courier New', monospace",
    "[python]": {
        "editor.formatOnType": true
    },
    "explorer.confirmDragAndDrop": false,
    "terminal.integrated.defaultProfile.windows": "Git Bash",
    "git.confirmSync": false,
    "editor.fontLigatures": false,
    "debug.console.fontFamily": "Cartograph CF",
    "[typescriptreact]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "[html]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "markdown.preview.fontFamily": "SF Pro Display",
    "[javascript]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "[typescript]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "typescript.updateImportsOnFileMove.enabled": "always",
    "[javascriptreact]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "[json]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "terminal.integrated.env.windows": {},
    "[css]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "emmet.includeLanguages": {
        "javascript": "javascriptreact"
    },
    "editor.tabSize": 3,
    "editor.guides.indentation": false,
    "[jsonc]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "terminal.integrated.env.linux": {},
    "terminal.integrated.defaultProfile.linux": "bash (2)",
    "terminal.external.linuxExec": "Terminal",
    "terminal.integrated.profiles.linux": {
        "bash": {
            "path": "bash",
            "icon": "terminal-bash"
        },
        "zsh": {
            "path": "zsh"
        },
        "fish": {
            "path": "fish"
        },
        "tmux": {
            "path": "tmux",
            "icon": "terminal-tmux"
        },
        "pwsh": {
            "path": "pwsh",
            "icon": "terminal-powershell"
        },
        "bash (2)": {
            "path": "/usr/bin/bash"
        }
    },
    "terminal.integrated.fontFamily": "Cartograph CF",
    "terminal.integrated.fontSize": 13.5,
    "editor.fontSize": 14,
    "update.mode": "start",
    "workbench.editor.enablePreview": false,
    "terminal.integrated.defaultProfile.osx": "zsh",
    "editor.unicodeHighlight.allowedCharacters": {
        "‎": true
    },
    "editor.unicodeHighlight.includeStrings": false,
    "window.titleBarStyle": "custom",
    "workbench.colorTheme": "Noir Rosé Pine Moon Grey"
}
`

**Comment by oeuvars** [comment]
Yes, Here is my settings.json

```
{
    "security.workspace.trust.untrustedFiles": "open",
    "files.trimTrailingWhitespace": true,
    "files.insertFinalNewline": true,
    "editor.rulers": [
        120
    ],
    "explorer.confirmDelete": false,
    "editor.minimap.enabled": false,
    "terminal.explorerKind": "external",
    "terminal.integrated.allowMnemonics": true,
    "terminal.integrated.cursorStyle": "line",
    "emmet.triggerExpansionOnTab": true,
    "workbench.settings.openDefaultKeybindings": true,
    "debug.onTaskErrors": "debugAnyway",
    "editor.fontWeight": 400,
    "editor.scrollBeyondLastLine": false,
    "files.autoSaveDelay": 1,
    "terminal.integrated.fontWeight": 400,
    "terminal.integrated.fontWeightBold": 400,
    "terminal.integrated.lineHeight": 1.3,
    "editor.lineHeight": 1.5,
    "editor.tokenColorCustomizations": {

        "[Rosé Pine]": {
            "textMateRules": [
                {
                    "scope": [
                        "comment",
                        "entity.other.attribute-name",
                        "entity.other.inherited-class",
                        "support.function",
                        "variable",
                        "meta.directive.vue"
                    ],
                    "settings": {
                        "fontStyle": "bold"
                    }
                }
            ]
        },
        "textMateRules": [
            {
                "name": "One Dark italic",
                "scope": [
                    "comment",
                    "entity.other.attribute-name",
                    "keyword",
                    "markup.underline.link",
                    "storage.modifier",
                    "storage.type",
                    "string.url",
                    "variable.language.super",
                    "variable.language.this"
                ],
                "settings": {
                    "fontStyle": "italic"
                }
            },
            {
                "name": "One Dark italic reset",
                "scope": [
                    "keyword.operator",
                    "keyword.other.type",
                    "storage.modifier.import",
                    "storage.modifier.package",
                    "storage.type.built-in",
                    "storage.type.function.arrow",
                    "storage.type.generic",
                    "storage.type.java",
                    "storage.type.primitive"
                ],
                "settings": {
                    "fontStyle": ""
                }
            }
        ]
    },
    "tailwindCSS.experimental.configFile": null,
    "editor.quickSuggestions": {
        "strings": "on"
    },
    "editor.linkedEditing": true,
    "terminal.integrated.gpuAcceleration": "off",
    "terminal.integrated.autoReplies": {

    },
    "editor.fontVariations": false,
    "workbench.startupEditor": "none",
    "javascript.updateImportsOnFileMove.enabled": "always",
    "editor.accessibilitySupport": "off",
    "git.autofetch": true,
    "editor.inlayHints.fontFamily": "Helvetica",
    "terminal.integrated.enableMultiLinePasteWarning": false,
    "workbench.iconTheme": "helium-icon-theme",
    "editor.fontFamily": "Cartograph CF, 'Courier New', monospace",
    "[python]": {
        "editor.formatOnType": true
    },
    "explorer.confirmDragAndDrop": false,
    "terminal.integrated.defaultProfile.windows": "Git Bash",
    "git.confirmSync": false,
    "editor.fontLigatures": false,
    "debug.console.fontFamily": "Cartograph CF",
    "[typescriptreact]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "[html]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "markdown.preview.fontFamily": "SF Pro Display",
    "[javascript]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "[typescript]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "typescript.updateImportsOnFileMove.enabled": "always",
    "[javascriptreact]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "[json]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "terminal.integrated.env.windows": {},
    "[css]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "emmet.includeLanguages": {
        "javascript": "javascriptreact"
    },
    "editor.tabSize": 3,
    "editor.guides.indentation": false,
    "[jsonc]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "terminal.integrated.env.linux": {},
    "terminal.integrated.defaultProfile.linux": "bash (2)",
    "terminal.external.linuxExec": "Terminal",
    "terminal.integrated.profiles.linux": {
        "bash": {
            "path": "bash",
            "icon": "terminal-bash"
        },
        "zsh": {
            "path": "zsh"
        },
        "fish": {
            "path": "fish"
        },
        "tmux": {
            "path": "tmux",
            "icon": "terminal-tmux"
        },
        "pwsh": {
            "path": "pwsh",
            "icon": "terminal-powershell"
        },
        "bash (2)": {
            "path": "/usr/bin/bash"
        }
    },
    "terminal.integrated.fontFamily": "Cartograph CF",
    "terminal.integrated.fontSize": 13.5,
    "editor.fontSize": 14,
    "update.mode": "start",
    "workbench.editor.enablePreview": false,
    "terminal.integrated.defaultProfile.osx": "zsh",
    "editor.unicodeHighlight.allowedCharacters": {
        "‎": true
    },
    "editor.unicodeHighlight.includeStrings": false,
    "window.titleBarStyle": "custom",
    "workbench.colorTheme": "Noir Rosé Pine Moon Grey"
}
```

**Comment by andrewberty** [comment]
I copied your entire config into my editor and still can't seem to replicate that darker space. I'm currently using windows. Don't know if it maybe a thing in vscode in macOS. I will surely test it further when I get an access to macOS.

![Code_nKuSBvEDsq](https://github.com/andrew-george/Noir-vscode-theme/assets/95014217/967caa73-f9be-4ae0-8557-7b2cce1f36b6)

Meanwhile. Thank you so much for your communication. Also, I'm really glad that you like the extension.

I will close that issue for now as I can't replicate it. If you're still facing any issues or have any ideas don't hesitate to start another issue.

Best Regards

**Comment by oeuvars** [comment]
Oh, I understand. Yeah I also noticed those dark spaces do not appear on windows machines. Thank you for looking into it though, cheers.
