### ISSUE TITLE
Increase the color contrast of comment text.

### ISSUE THREAD

**Issue by content-aruna** [andrew-george/Noir-vscode-theme#3]
Hello developer, I am fascinated with the Nor Tokyo Night theme, but there is a small issue with the comment text's low color contrast. Could you fix this soon?

**Comment by andrew-george** [comment]
`
"editor.tokenColorCustomizations": {
  "[Noir Tokyo Night]" : {
    "textMateRules": [
      {
        "scope": ["comment"],
        "settings": {
        }
      }
    ]
  }
}
`

**Comment by andrewberty** [comment]
Hello @me-aruna , well comments should be more invisible than your actual code. but if you prefer more bright color for comments you can easily tweak that in your vscode settings.json by adding this 

```json
"editor.tokenColorCustomizations": {
    "[Noir Tokyo Night]": {
      "textMateRules": [
        {
          "scope": ["comment"],
          "settings": {
            "foreground": "#FF0000"
          }
        }
      ]
    }
  }
```

**Comment by content-aruna** [comment]
> Hello @me-aruna , well comments should be more invisible than your actual code. but if you prefer more bright color for comments you can easily tweak that in your vscode settings.json by adding this
> 
> ```json
> "editor.tokenColorCustomizations": {
>     "[Noir Tokyo Night]": {
>       "textMateRules": [
>         {
>           "scope": ["comment"],
>           "settings": {
>             "foreground": "#FF0000"
>           }
>         }
>       ]
>     }
>   }
> ```

 Thanks for your response @andrew-george , Your code was very helpful to me.

**Comment by andrewberty** [comment]
Thanks and happy coding!

I'm gonna close this issue for now, but if you found any bugs or had any ideas, don't hesitate to open another issue.
